services:
  - type: web
    name: kawan-tani-backend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production

      - key: DATABASE_URL
      - key: JWT_SECRET
